name: atcd_choreo_sync
description: Automatically download choreographies from ATCD Discord

publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  sqflite_common_ffi: ^2.2.5
  sqlite3_flutter_libs: ^0.5.15
  sqflite: ^2.2.8+4
  mutex: ^3.0.1
  csv: ^5.0.2
  http: ^0.13.6
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  win32: ^4.1.4
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.2
  flutter_search_bar: ^3.0.0-dev.1
  dio: ^5.1.2
  archive: ^3.3.7
  tuple: ^2.0.1
  prompt_dialog: ^1.0.10
  package_info_plus: ^4.0.1
  url_launcher: ^6.1.11
  device_apps: ^2.2.0
  device_info_plus: ^9.0.1
  saf: ^1.0.3+4
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  pigeon: ^10.0.0
  yaml: ^3.1.2

flutter:
  uses-material-design: true
