// Autogenerated from Pigeon (v2.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package club.atcd.choreo_sync.p7zip;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class P7ZipExtractorPigeon {
  private static class P7ZipExtractorAndroidCodec extends StandardMessageCodec {
    public static final P7ZipExtractorAndroidCodec INSTANCE = new P7ZipExtractorAndroidCodec();
    private P7ZipExtractorAndroidCodec() {}
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface P7ZipExtractorAndroid {
    @NonNull List<String> extractArchive(@NonNull String archivePath, @NonNull String outputDir);

    /** The codec used by P7ZipExtractorAndroid. */
    static MessageCodec<Object> getCodec() {
      return P7ZipExtractorAndroidCodec.INSTANCE;
    }

    /** Sets up an instance of `P7ZipExtractorAndroid` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, P7ZipExtractorAndroid api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.P7ZipExtractorAndroid.extractArchive", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              String archivePathArg = (String)args.get(0);
              if (archivePathArg == null) {
                throw new NullPointerException("archivePathArg unexpectedly null.");
              }
              String outputDirArg = (String)args.get(1);
              if (outputDirArg == null) {
                throw new NullPointerException("outputDirArg unexpectedly null.");
              }
              List<String> output = api.extractArchive(archivePathArg, outputDirArg);
              wrapped.put("result", output);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    return errorMap;
  }
}
