name: Quest/Android build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
          
      - name: Download Dart/Flutter dependencies
        run: cd atcd_choreo_sync && flutter pub get
        
      - name: Build debug APK
        run: cd atcd_choreo_sync && flutter build apk
        
      - name: Build debug AAB
        run: cd atcd_choreo_sync && flutter build appbundle
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app_debug
          # The filenames say "release" but they're signed with the debug keys
          path: |
            atcd_choreo_sync/build/app/outputs/flutter-apk/app-release.apk
            atcd_choreo_sync/build/app/outputs/bundle/release/app-release.aab
          
