name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  build-android:
    name: "Quest/Android"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
      
      - name: Build app
        run: |
          flutter build apk
          flutter build appbundle
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app_android
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  build-windows:
    name: "Windows"
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
      
      - name: Build app
        shell: bash
        run: |
          flutter config --enable-windows-desktop
          flutter build windows
          curl https://github.com/tekartik/sqflite/raw/master/sqflite_common_ffi/lib/src/windows/sqlite3.dll > build/windows/runner/Release/sqlite3.dll
               
      - name: Upload build
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app_windows
          path: build/windows/runner/Release/

  build-linux:
    name: "Linux AppImage build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
      
      - name: Build app
        run: |
          flutter config --enable-linux-desktop
          flutter build linux

      - name: Prepare AppDir for AppImage
        uses: AppImageCrafters/build-appimage@master
        with:
          recipe: linux/AppImageBuilder.yml
          args: --skip-appimage

      - name: Pack AppImage
        run: |
          sudo chown -R $(id -u):$(id -g) .
          cp linux/AppRun AppDir/AppRun  # appimage-builder's AppRun breaks Wayland
          curl -L https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage > appimagetool.AppImage
          chmod +x appimagetool.AppImage
          ARCH=x86_64 ./appimagetool.AppImage AppDir 'atcd_choreo_sync.AppImage'

      - name: Upload build
        uses: actions/upload-artifact@v3.0.0
        with:
          name: appimage_linux
          path: atcd_choreo_sync.AppImage

